### PR TITLE
Enable AutoLoading and add bulk method of original repo.

### PR DESCRIPTION
**Pull request by mvedie**
A composer lib without autoloading is less usable . So this pull request fix this and add the new functions on the master branch of cloudscrape/cloudscraper-client-php (bulk methods).

Please merge this pull for your customers... (we are customer :) )

### CODE REVIEW

**Comment by devdce** [comment]
Please examine your client's Pull Request .. !

**Comment by hofmeister** [comment]
Hi @mvedie @devdce and @samlev - very sorry that we completely dropped the ball on merging these highly appreciated pull requests. If you can make them not conflict with the master branch we'll get them merged asap.

**Comment by mvedie** [comment]
Okays, it's ready to merge :)

**Comment by hofmeister** [comment]
Perfect thanks !

**Pull request merged**
